### PR TITLE
Application port tutorial4 module 2

### PR DESCRIPTION
**Pull request by danpham02**

### CODE REVIEW

**Comment by MartyCarroll** [comment]
image

I get this when I try to run the thing. Not sure if "audio session" is Android only.
Would something like https://flutterawesome.com/just_audio-a-feature-rich-audio-player-for-android-ios-macos-web-linux-and-windows/ work better instead?

**Comment by danpham02** [comment]
ill investigate this tomorrow, but as of right now im already using the just_audio plugin for this module
image

it seems like audio_session is a dependency of just_audio which should work on ios and android anyway according to documentation
image

**Comment by byebrid** [comment]
Just added some small fixes in 9bef07f, but this seems really good! I think just make sure that final merge commit states that it's just module 2 from tutorial 4, and not module 1 or 3 (which were obvs omitted for good reason).

**Comment by byebrid** [comment]
I can see that you've used the `tts` plugin to replace `SemanticsService.announce()` in some parts. I think we'll still want to use simple text elements to store instructions so the user can replay them at any time just by navigating back to them, but perhaps we need to discuss `tts` vs normal semantics as a team. Also, I find the text-to-speech is much quieter than the actual talkback which is a definite downside.

However, I think this is absolutely good enough to merge now, just note that we'll likely want to make changes to the text-to-speech later.

**Comment by byebrid** [comment]
@danpham02 could you please confirm that this still works on your end after I've resolved that merge conflict? If so, feel free to merge this request.

**Review by byebrid — APPROVED** [review]

**Pull request merged**
