### PR TITLE
Application port tutorial4 module1

### PR DESCRIPTION
**Pull request by ssah0022**
As I can't run the application myself (cocoapods issues, still trying to solve them) it would be nice if someone else could review my work

### CODE REVIEW

**Comment by byebrid** [comment]
There are still a few things to fix:
- I don't see any video being played. 
- I also didn't hear the instructions when I entered the module. 
- What is the button in the bottom-right meant to do? When I tap it, it just says "great job, you have played the video". Shouldn't we be using the built-in video player as opposed to some button elsewhere on the screen, to make it more realistic?

image

**Comment by byebrid** [comment]
I simply get a full emulator crash when I try to open up that module in Tutorial 4. I'll leave the full log down below.

This was tested with a Pixel 4 API 30 on the android emulator.

```
Launching lib/main.dart on sdk gphone x86 in debug mode...
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:38573/wlMb9PH7NC4=/ws
I/ExoPlayerImpl( 5309): Init 49702ba [ExoPlayerLib/2.18.5] [generic_x86_arm, sdk_gphone_x86, Google, 30]
W/ple.applicatio( 5309): Accessing hidden method Landroid/media/AudioTrack;->getLatency()I (greylist, reflection, allowed)
I/TetheringManager( 5309): registerTetheringEventCallback:com.example.application
D/TTS     ( 5309): Utterance ID has been stopped: e7452ef4-7503-475a-9102-749231185db9. Interrupted: true
I/VideoCapabilities( 5309): Unsupported profile 4 for video/mp4v-es
I/OMXClient( 5309): IOmx service obtained
D/SurfaceUtils( 5309): connecting to surface 0xb5987e08, reason connectToSurface
I/MediaCodec( 5309): [OMX.android.goldfish.h264.decoder] setting surface generation to 5436417
D/SurfaceUtils( 5309): disconnecting from surface 0xb5987e08, reason connectToSurface(reconnect)
D/SurfaceUtils( 5309): connecting to surface 0xb5987e08, reason connectToSurface(reconnect)
E/ACodec  ( 5309): [OMX.android.goldfish.h264.decoder] setPortMode on output to DynamicANWBuffer failed w/ err -1010
I/ACodec  ( 5309): codec does not support config priority (err -1010)
I/ACodec  ( 5309): codec does not support config operating rate (err -1010)
D/SurfaceUtils( 5309): disconnecting from surface 0xb5987e08, reason setNativeWindowSizeFormatAndUsage
D/SurfaceUtils( 5309): connecting to surface 0xb5987e08, reason setNativeWindowSizeFormatAndUsage
D/SurfaceUtils( 5309): set up nativeWindow 0xb5987e08 for 1080x1920, color 0x13, rotation 0, usage 0x1002900
W/Gralloc4( 5309): allocator 3.x is not supported
D/CCodec  ( 5309): allocate(c2.android.aac.decoder)
I/Codec2Client( 5309): Available Codec2 services: "software"
I/CCodec  ( 5309): Created component [c2.android.aac.decoder]
D/CCodecConfig( 5309): read media type: audio/mp4a-latm
D/ReflectedParamUpdater( 5309): extent() != 1 for single value type: algo.buffers.max-count.values
D/ReflectedParamUpdater( 5309): extent() != 1 for single value type: output.subscribed-indices.values
D/ReflectedParamUpdater( 5309): extent() != 1 for single value type: input.buffers.allocator-ids.values
D/ReflectedParamUpdater( 5309): extent() != 1 for single value type: output.buffers.allocator-ids.values
D/ReflectedParamUpdater( 5309): extent() != 1 for single value type: algo.buffers.allocator-ids.values
D/ReflectedParamUpdater( 5309): extent() != 1 for single value type: output.buffers.pool-ids.values
D/ReflectedParamUpdater( 5309): extent() != 1 for single value type: algo.buffers.pool-ids.values
I/CCodecConfig( 5309): query failed after returning 19 values (BAD_INDEX)
D/CCodecConfig( 5309): c2 config diff is Dict {
D/CCodecConfig( 5309):   c2::u32 coded.aac-packaging.value = 0
D/CCodecConfig( 5309):   c2::u32 coded.bitrate.value = 64000
D/CCodecConfig( 5309):   c2::u32 coded.pl.level = 0
D/CCodecConfig( 5309):   c2::u32 coded.pl.profile = 8192
D/CCodecConfig( 5309):   c2::i32 coding.drc.album-mode.value = 0
D/CCodecConfig( 5309):   c2::float coding.drc.attenuation-factor.value = 1
D/CCodecConfig( 5309):   c2::float coding.drc.boost-factor.value = 1
D/CCodecConfig( 5309):   c2::i32 coding.drc.compression-mode.value = 3
D/CCodecConfig( 5309):   c2::i32 coding.drc.effect-type.value = 3
D/CCodecConfig( 5309):   c2::float coding.drc.encoded-level.value = 0.25
D/CCodecConfig( 5309):   c2::float coding.drc.reference-level.value = -16
D/CCodecConfig( 5309):   c2::u32 input.buffers.max-size.value = 8192
D/CCodecConfig( 5309):   c2::u32 input.delay.value = 0
D/CCodecConfig( 5309):   string input.media-type.value = "audio/mp4a-latm"
D/CCodecConfig( 5309):   c2::u32 output.delay.value = 2
D/CCodecConfig( 5309):   c2::float output.drc.output-loudness.value = 0.25
D/CCodecConfig( 5309):   string output.media-type.value = "audio/raw"
D/CCodecConfig( 5309):   c2::u32 raw.channel-count.value = 1
D/CCodecConfig( 5309):   c2::u32 raw.max-channel-count.value = 8
D/CCodecConfig( 5309):   c2::u32 raw.sample-rate.value = 44100
D/CCodecConfig( 5309): }
D/CCodec  ( 5309): [c2.android.aac.decoder] buffers are bound to CCodec for this session
D/CCodecConfig( 5309): no c2 equivalents for flags
D/CCodecConfig( 5309): config failed => CORRUPTED
D/CCodecConfig( 5309): c2 config diff is   c2::u32 raw.channel-count.value = 2
D/CCodecConfig( 5309):   c2::u32 raw.sample-rate.value = 48000
W/Codec2Client( 5309): query -- param skipped: index = 1107298332.
D/CCodec  ( 5309): client requested max input size 959, which is smaller than what component recommended (8192); overriding with component recommendation.
W/CCodec  ( 5309): This behavior is subject to change. It is recommended that app developers double check whether the requested max input size is in reasonable range.
D/CCodec  ( 5309): setup formats input: AMessage(what = 0x00000000) = {
D/CCodec  ( 5309):   int32_t aac-drc-album-mode = 0
D/CCodec  ( 5309):   int32_t aac-drc-boost-level = 127
D/CCodec  ( 5309):   int32_t aac-drc-cut-level = 127
D/CCodec  ( 5309):   int32_t aac-drc-effect-type = 3
D/CCodec  ( 5309):   int32_t aac-drc-heavy-compression = 3
D/CCodec  ( 5309):   int32_t aac-encoded-target-level = -1
D/CCodec  ( 5309):   int32_t aac-max-output-channel_count = 8
D/CCodec  ( 5309):   int32_t aac-target-ref-level = 64
D/CCodec  ( 5309):   int32_t channel-count = 2
D/CCodec  ( 5309):   int32_t level = 0
D/CCodec  ( 5309):   int32_t max-input-size = 8192
D/CCodec  ( 5309):   string mime = "audio/mp4a-latm"
D/CCodec  ( 5309):   int32_t profile = 2
D/CCodec  ( 5309):   int32_t sample-rate = 48000
D/CCodec  ( 5309): } and output: AMessage(what = 0x00000000) = {
D/CCodec  ( 5309):   int32_t aac-drc-album-mode = 0
D/CCodec  ( 5309):   int32_t aac-drc-boost-level = 127
D/CCodec  ( 5309):   int32_t aac-drc-cut-level = 127
D/CCodec  ( 5309):   int32_t aac-drc-effect-type = 3
D/CCodec  ( 5309):   int32_t aac-drc-heavy-compression = 3
D/CCodec  ( 5309):   int32_t aac-drc-output-loudness = -1
D/CCodec  ( 5309):   int32_t aac-encoded-target-level = -1
D/CCodec  ( 5309):   int32_t aac-max-output-channel_count = 8
D/CCodec  ( 5309):   int32_t aac-target-ref-level = 64
D/CCodec  ( 5309):   int32_t channel-count = 2
D/CCodec  ( 5309):   string mime = "audio/raw"
D/CCodec  ( 5309):   int32_t sample-rate = 48000
D/CCodec  ( 5309): }
W/Codec2Client( 5309): query -- param skipped: index = 1342179345.
W/Codec2Client( 5309): query -- param skipped: index = 2415921170.
W/Codec2Client( 5309): query -- param skipped: index = 1610614798.
E/FMQ     ( 5309): grantorIdx must be less than 3
E/FMQ     ( 5309): grantorIdx must be less than 3
D/CCodecBufferChannel( 5309): [c2.android.aac.decoder#918] Created input block pool with allocatorID 16 => poolID 17 - OK (0)
I/CCodecBufferChannel( 5309): [c2.android.aac.decoder#918] Created output block pool with allocatorID 16 => poolID 34 - OK
D/CCodecBufferChannel( 5309): [c2.android.aac.decoder#918] Configured output block pool ids 34 => OK
E/ion     ( 5309): ioctl c0044901 failed with code -1: Inappropriate ioctl for device
E/FMQ     ( 5309): grantorIdx must be less than 3
Lost connection to device.
Exited (sigterm)
```

Edited to add: here's a shorter log from running it a second time. Every actual log message was only generated when I tapped the button to open up the module.

```
Launching lib/main.dart on sdk gphone x86 in debug mode...
main.dart:1
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:44979/zzX8haGwFT0=/ws
I/ExoPlayerImpl( 3263): Init fbe0ce4 [ExoPlayerLib/2.18.5] [generic_x86_arm, sdk_gphone_x86, Google, 30]
W/ple.applicatio( 3263): Accessing hidden method Landroid/media/AudioTrack;->getLatency()I (greylist, reflection, allowed)
I/TetheringManager( 3263): registerTetheringEventCallback:com.example.application
D/TTS     ( 3263): Utterance ID has been stopped: 222ac22a-4f64-4ab5-a212-8ed1162a2407. Interrupted: true
I/VideoCapabilities( 3263): Unsupported profile 4 for video/mp4v-es
I/OMXClient( 3263): IOmx service obtained
D/SurfaceUtils( 3263): connecting to surface 0xba7c64d8, reason connectToSurface
I/MediaCodec( 3263): [OMX.android.goldfish.h264.decoder] setting surface generation to 3341313
D/SurfaceUtils( 3263): disconnecting from surface 0xba7c64d8, reason connectToSurface(reconnect)
D/SurfaceUtils( 3263): connecting to surface 0xba7c64d8, reason connectToSurface(reconnect)
E/ACodec  ( 3263): [OMX.android.goldfish.h264.decoder] setPortMode on output to DynamicANWBuffer failed w/ err -1010
I/ACodec  ( 3263): codec does not support config priority (err -1010)
I/ACodec  ( 3263): codec does not support config operating rate (err -1010)
D/SurfaceUtils( 3263): disconnecting from surface 0xba7c64d8, reason setNativeWindowSizeFormatAndUsage
D/SurfaceUtils( 3263): connecting to surface 0xba7c64d8, reason setNativeWindowSizeFormatAndUsage
D/SurfaceUtils( 3263): set up nativeWindow 0xba7c64d8 for 1080x1920, color 0x13, rotation 0, usage 0x1002900
W/Gralloc4( 3263): allocator 3.x is not supported
Lost connection to device.
Exited (sigterm)
```

**Comment by byebrid** [comment]
Haven't checked to see if ExoPlayer is being used here, but if so then [this issue](https://github.com/google/ExoPlayer/issues/886) states that emulator support for playback is just not very good. So would perhaps be good to have someone check with a physical Android device here.

**Comment by byebrid** [comment]
Just confirmed that the flutter `video_player` extension is indeed relying on ExoPlayer for Android.

image

**Comment by haotongwang** [comment]
please make a pr to ApplicationPort (our feature branch) rather than main

**Comment by byebrid** [comment]
Marked as draft just to show there are still some things to figure out here

**Comment by byebrid** [comment]
Tested on Pixel 4 API 34 android emulator.

Still doesn't work on my end. I can get into the module but only see the following:
image

I can't navigate with talkback to anything other than the header of the page. I'll dump my debug log at the end of this just for the record. I do see a few warnings here and there but haven't looked too closely at them, and didn't spot any fatal error messages (but I did see "CORRUPTED" config somewhere).

Can you please confirm that it does successfully run on your end? What android emulator are you using if so? Does it run for other people in your team? Thanks in advance.

```
Launching lib/main.dart on sdk gphone64 x86 64 in debug mode...
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
E/OpenGLRenderer(17029): Unable to match the desired swap behavior.
Connecting to VM Service at ws://127.0.0.1:42419/AdQmE79KDdM=/ws
D/EGL_emulation(17029): app_time_stats: avg=475.98ms min=244.15ms max=1180.09ms count=5
D/EGL_emulation(17029): app_time_stats: avg=1517.17ms min=8.79ms max=3025.56ms count=2
D/EGL_emulation(17029): app_time_stats: avg=442.96ms min=121.68ms max=614.68ms count=3
D/EGL_emulation(17029): app_time_stats: avg=151.22ms min=3.19ms max=1513.97ms count=11
I/ExoPlayerImpl(17029): Init df55049 [ExoPlayerLib/2.18.5] [emu64xa, sdk_gphone64_x86_64, Google, 34]
W/ple.application(17029): Accessing hidden method Landroid/media/AudioTrack;->getLatency()I (unsupported, reflection, allowed)
I/Surface (17029): Surface::setFrameRate is deprecated, setFrameRate hint is dropped as destination is not SurfaceFlinger
D/EGL_emulation(17029): app_time_stats: avg=603.65ms min=312.18ms max=895.12ms count=2
D/TTS     (17029): Utterance ID has been stopped: 7a82ee83-7dcb-4eb4-8765-f39a1629f8ba. Interrupted: true
D/MediaCodecInfo(17029): NoSupport [sizeAndRate.cover, 1080x1920@60.0] [c2.goldfish.h264.decoder, video/avc] [emu64xa, sdk_gphone64_x86_64, Google, 34]
D/MediaCodecInfo(17029): NoSupport [sizeAndRate.cover, 1080x1920@60.0] [c2.goldfish.h264.decoder, video/avc] [emu64xa, sdk_gphone64_x86_64, Google, 34]
I/DMCodecAdapterFactory(17029): Creating an asynchronous MediaCodec adapter for track type video
D/CCodec  (17029): allocate(c2.goldfish.h264.decoder)
I/Codec2Client(17029): Available Codec2 services: "default" "software"
I/CCodec  (17029): setting up 'default' as default (vendor) store
I/CCodec  (17029): Created component [c2.goldfish.h264.decoder]
D/CCodecConfig(17029): read media type: video/avc
D/ReflectedParamUpdater(17029): extent() != 1 for single value type: algo.buffers.max-count.values
D/ReflectedParamUpdater(17029): extent() != 1 for single value type: output.subscribed-indices.values
D/ReflectedParamUpdater(17029): extent() != 1 for single value type: input.buffers.allocator-ids.values
D/ReflectedParamUpdater(17029): extent() != 1 for single value type: output.buffers.allocator-ids.values
D/ReflectedParamUpdater(17029): extent() != 1 for single value type: algo.buffers.allocator-ids.values
D/ReflectedParamUpdater(17029): extent() != 1 for single value type: output.buffers.pool-ids.values
D/ReflectedParamUpdater(17029): extent() != 1 for single value type: algo.buffers.pool-ids.values
D/ReflectedParamUpdater(17029): ignored struct field coded.color-format.locations
D/CCodecConfig(17029): ignoring local param raw.size (0xd2001800) as it is already supported
D/CCodecConfig(17029): ignoring local param default.color (0x5200180b) as it is already supported
D/ReflectedParamUpdater(17029): ignored struct field raw.hdr-static-info.mastering
I/CCodecConfig(17029): query failed after returning 12 values (BAD_INDEX)
D/CCodecConfig(17029): c2 config diff is Dict {
D/CCodecConfig(17029):   c2::u32 coded.pl.level = 20496
D/CCodecConfig(17029):   c2::u32 coded.pl.profile = 20481
D/CCodecConfig(17029):   c2::u32 coded.vui.color.matrix = 0
D/CCodecConfig(17029):   c2::u32 coded.vui.color.primaries = 0
D/CCodecConfig(17029):   c2::u32 coded.vui.color.range = 2
D/CCodecConfig(17029):   c2::u32 coded.vui.color.transfer = 0
D/CCodecConfig(17029):   c2::u32 default.color.matrix = 0
D/CCodecConfig(17029):   c2::u32 default.color.primaries = 0
D/CCodecConfig(17029):   c2::u32 default.color.range = 0
D/CCodecConfig(17029):   c2::u32 default.color.transfer = 0
D/CCodecConfig(17029):   c2::u32 input.buffers.max-size.value = 6291456
D/CCodecConfig(17029):   c2::u32 input.delay.value = 0
D/CCodecConfig(17029):   string input.media-type.value = "video/avc"
D/CCodecConfig(17029):   c2::u32 output.delay.value = 8
D/CCodecConfig(17029):   string output.media-type.value = "video/raw"
D/CCodecConfig(17029):   c2::u32 raw.color.matrix = 0
D/CCodecConfig(17029):   c2::u32 raw.color.primaries = 0
D/CCodecConfig(17029):   c2::u32 raw.color.range = 2
D/CCodecConfig(17029):   c2::u32 raw.color.transfer = 0
D/CCodecConfig(17029):   c2::u32 raw.max-size.height = 240
D/CCodecConfig(17029):   c2::u32 raw.max-size.width = 320
D/CCodecConfig(17029):   c2::u32 raw.pixel-format.value = 35
D/CCodecConfig(17029):   c2::i32 raw.rotation.flip = 0
D/CCodecConfig(17029):   c2::i32 raw.rotation.value = 0
D/CCodecConfig(17029):   c2::u32 raw.sar.height = 1
D/CCodecConfig(17029):   c2::u32 raw.sar.width = 1
D/CCodecConfig(17029):   c2::u32 raw.size.height = 240
D/CCodecConfig(17029):   c2::u32 raw.size.width = 320
D/CCodecConfig(17029):   c2:
W/ColorUtils(17029): expected specified color aspects (2:0:0:0)
I/MediaCodec(17029): MediaCodec will operate in async mode
D/MediaCodec(17029): flushMediametrics
D/SurfaceUtils(17029): connecting to surface 0x7d998410e640, reason connectToSurface
I/MediaCodec(17029): [c2.goldfish.h264.decoder] setting surface generation to 17437697
D/SurfaceUtils(17029): disconnecting from surface 0x7d998410e640, reason connectToSurface(reconnect)
D/SurfaceUtils(17029): connecting to surface 0x7d998410e640, reason connectToSurface(reconnect)
D/CCodec  (17029): [c2.goldfish.h264.decoder] buffers are bound to CCodec for this session
D/CCodecConfig(17029): no c2 equivalents for log-session-id
D/CCodecConfig(17029): no c2 equivalents for color-standard
D/CCodecConfig(17029): no c2 equivalents for csd-1
D/CCodecConfig(17029): no c2 equivalents for native-window
D/CCodecConfig(17029): no c2 equivalents for flags
D/CCodecConfig(17029): config failed => CORRUPTED
D/CCodecConfig(17029): c2 config diff is   c2::u32 default.color.matrix = 1
D/CCodecConfig(17029):   c2::u32 default.color.primaries = 1
D/CCodecConfig(17029):   c2::u32 default.color.range = 2
D/CCodecConfig(17029):   c2::u32 default.color.transfer = 3
D/CCodecConfig(17029):   c2::u32 raw.max-size.height = 1920
D/CCodecConfig(17029):   c2::u32 raw.max-size.width = 1080
D/CCodecConfig(17029):   c2::u32 raw.size.height = 1920
D/CCodecConfig(17029):   c2::u32 raw.size.width = 1080
W/Codec2Client(17029): query -- param skipped: index = 1107298332.
D/CCodec  (17029): client requested max input size 273846, which is smaller than what component recommended (6291456); overriding with component recommendation.
W/CCodec  (17029): This behavior is subject to change. It is recommended that app developers double check whether the requested max input size is in reasonable range.
D/CCodec  (17029): encoding statistics level = 0
D/CCodec  (17029): setup formats input: AMessage(what = 0x00000000) = {
D/CCodec  (17029):   int32_t height = 1920
D/CCodec  (17029):   int32_t level = 65536
D/CCodec  (17029):   int32_t max-input-size = 6291456
D/CCodec  (17029):   string mime = "video/avc"
D/CCodec  (17029):   int32_t profile = 65536
D/CCodec  (17029):   int32_t width = 1080
D/CCodec  (17029):   Rect crop(0, 0, 1079, 1919)
D/CCodec  (17029): }
D/CCodec  (17029): setup formats output: AMessage(what = 0x00000000) = {
D/CCodec  (17029):   int32_t android._color-format = 2135033992
D/CCodec  (17029):   int32_t android._video-scaling = 1
D/CCodec  (17029):   int32_t rotation-degrees = 0
D/CCodec  (17029):   int32_t color-standard = 1
D/CCodec  (17029):   int32_t color-range = 2
D/CCodec  (17029):   int32_t color-transfer = 3
D/CCodec  (17029):   int32_t sar-height = 1
D/CCodec  (17029):   int32_t sar-width = 1
D/CCodec  (17029):   Rect crop(0, 0, 1079, 1919)
D/CCodec  (17029):   int32_t width = 1080
D/CCodec  (17029):   int32_t height = 1920
D/CCodec  (17029):   int32_t max-height = 1920
D/CCodec  (17029):   int32_t max-width = 1080
D/CCodec  (17029):   string mime = "video/raw"
D/CCodec  (17029):   int32_t android._dataspace = 260
D/CCodec  (17029):   int32_t color-format = 2130708361
D/CCodec  (17029): }
I/CCodecConfig(17029): query failed after returning 12 values (BAD_INDEX)
D/CCodecConfig(17029): c2 config diff is   c2::u32 raw.color.matrix = 1
D/CCodecConfig(17029):   c2::u32 raw.color.primaries = 1
D/CCodecConfig(17029):   c2::u32 raw.color.transfer = 3
D/MediaCodec(17029): keep callback message for reclaim
W/Codec2Client(17029): query -- param skipped: index = 1342179345.
W/Codec2Client(17029): query -- param skipped: index = 2415921170.
W/Codec2Client(17029): query -- param skipped: index = 1610614798.
W/Codec2Client(17029): query -- param skipped: index = 2684356609.
D/C2Store (17029): Using DMABUF Heaps
D/CCodecBufferChannel(17029): [c2.goldfish.h264.decoder#422] Created input block pool with allocatorID 16 => poolID 17 - OK (0)
D/CCodecBufferChannel(17029): [c2.goldfish.h264.decoder#422] Query output surface allocator returned 0 params => BAD_INDEX (6)
I/CCodecBufferChannel(17029): [c2.goldfish.h264.decoder#422] Created output block pool with allocatorID 18 => poolID 17 - OK
D/CCodecBufferChannel(17029): [c2.goldfish.h264.decoder#422] Configured output block pool ids 17 => OK
D/Codec2-OutputBufferQueue(17029): remote graphic buffer migration 0/0
D/Codec2Client(17029): setOutputSurface -- failed to set consumer usage (6/BAD_INDEX)
D/Codec2Client(17029): setOutputSurface -- generation=17437697 consumer usage=0x900
D/Codec2Client(17029): Surface configure completed
I/DMABUFHEAPS(17029): Using DMA-BUF heap named: system
D/MediaCodecInfo(17029): NoSupport [sizeAndRate.cover, 1080x1920@60.0] [c2.goldfish.h264.decoder, video/avc] [emu64xa, sdk_gphone64_x86_64, Google, 34]
W/MediaCodecRenderer(17029): Format exceeds selected codec's capabilities [id=1, mimeType=video/avc, codecs=avc1.64002A, res=1080x1920, fps=60.0, c2.goldfish.h264.decoder]
I/DMCodecAdapterFactory(17029): Creating an asynchronous MediaCodec adapter for track type audio
D/CCodec  (17029): allocate(c2.android.aac.decoder)
I/CCodec  (17029): setting up 'default' as default (vendor) store
D/EGL_emulation(17029): app_time_stats: avg=15.94ms min=6.49ms max=77.30ms count=20
I/CCodec  (17029): Created component [c2.android.aac.decoder]
D/CCodecConfig(17029): read media type: audio/mp4a-latm
D/ReflectedParamUpdater(17029): extent() != 1 for single value type: algo.buffers.max-count.values
D/ReflectedParamUpdater(17029): extent() != 1 for single value type: output.subscribed-indices.values
D/ReflectedParamUpdater(17029): extent() != 1 for single value type: input.buffers.allocator-ids.values
D/ReflectedParamUpdater(17029): extent() != 1 for single value type: output.buffers.allocator-ids.values
D/ReflectedParamUpdater(17029): extent() != 1 for single value type: algo.buffers.allocator-ids.values
D/ReflectedParamUpdater(17029): extent() != 1 for single value type: output.buffers.pool-ids.values
D/ReflectedParamUpdater(17029): extent() != 1 for single value type: algo.buffers.pool-ids.values
I/CCodecConfig(17029): query failed after returning 20 values (BAD_INDEX)
D/CCodecConfig(17029): c2 config diff is Dict {
D/CCodecConfig(17029):   c2::u32 coded.aac-packaging.value = 0
D/CCodecConfig(17029):   c2::u32 coded.bitrate.value = 64000
D/CCodecConfig(17029):   c2::u32 coded.pl.level = 0
D/CCodecConfig(17029):   c2::u32 coded.pl.profile = 8192
D/CCodecConfig(17029):   c2::i32 coding.drc.album-mode.value = 0
D/CCodecConfig(17029):   c2::float coding.drc.attenuation-factor.value = 1
D/CCodecConfig(17029):   c2::float coding.drc.boost-factor.value = 1
D/CCodecConfig(17029):   c2::i32 coding.drc.compression-mode.value = 3
D/CCodecConfig(17029):   c2::i32 coding.drc.effect-type.value = 3
D/CCodecConfig(17029):   c2::float coding.drc.encoded-level.value = 0.25
D/CCodecConfig(17029):   c2::float coding.drc.reference-level.value = -16
D/CCodecConfig(17029):   c2::u32 input.buffers.max-size.value = 8192
D/CCodecConfig(17029):   c2::u32 input.delay.value = 0
D/CCodecConfig(17029):   string input.media-type.value = "audio/mp4a-latm"
D/CCodecConfig(17029):   c2::u32 output.delay.value = 2
D/CCodecConfig(17029):   c2::float output.drc.output-loudness.value = 0.25
D/CCodecConfig(17029):   string output.media-type.value = "audio/raw"
D/CCodecConfig(17029):   c2::u32 raw.channel-count.value = 1
D/CCodecConfig(17029):   c2::u32 raw.channel-mask.value = 0
D/CCodecConfig(17029):   c2::u32 raw.max-channel-count.value = 8
D/CCodecConfig(17029):   c2::u32 raw.sample-rate.value = 44100
D/CCodecConfig(17029): }
I/MediaCodec(17029): MediaCodec will operate in async mode
D/MediaCodec(17029): flushMediametrics
D/CCodec  (17029): [c2.android.aac.decoder] buffers are bound to CCodec for this session
D/CCodecConfig(17029): no c2 equivalents for log-session-id
D/CCodecConfig(17029): no c2 equivalents for flags
D/CCodecConfig(17029): config failed => CORRUPTED
D/CCodecConfig(17029): c2 config diff is   c2::u32 raw.channel-count.value = 2
D/CCodecConfig(17029):   c2::u32 raw.sample-rate.value = 48000
W/Codec2Client(17029): query -- param skipped: index = 1107298332.
D/CCodec  (17029): client requested max input size 959, which is smaller than what component recommended (8192); overriding with component recommendation.
W/CCodec  (17029): This behavior is subject to change. It is recommended that app developers double check whether the requested max input size is in reasonable range.
D/CCodec  (17029): encoding statistics level = 0
D/CCodec  (17029): setup formats input: AMessage(what = 0x00000000) = {
D/CCodec  (17029):   int32_t aac-drc-album-mode = 0
D/CCodec  (17029):   int32_t aac-drc-boost-level = 127
D/CCodec  (17029):   int32_t aac-drc-cut-level = 127
D/CCodec  (17029):   int32_t aac-drc-effect-type = 3
D/CCodec  (17029):   int32_t aac-encoded-target-level = -1
D/CCodec  (17029):   int32_t aac-max-output-channel_count = 8
D/CCodec  (17029):   int32_t aac-target-ref-level = 64
D/CCodec  (17029):   int32_t bitrate = 64000
D/CCodec  (17029):   int32_t channel-count = 2
D/CCodec  (17029):   int32_t channel-mask = 0
D/CCodec  (17029):   int32_t level = 0
D/CCodec  (17029):   int32_t max-input-size = 8192
D/CCodec  (17029):   int32_t max-output-channel-count = 8
D/CCodec  (17029):   string mime = "audio/mp4a-latm"
D/CCodec  (17029):   int32_t profile = 2
D/CCodec  (17029):   int32_t sample-rate = 48000
D/CCodec  (17029): }
D/CCodec  (17029): setup formats output: AMessage(what = 0x00000000) = {
D/CCodec  (17029):   int32_t aac-drc-album-mode = 0
D/CCodec  (17029):   int32_t aac-drc-boost-level = 127
D/CCodec  (17029):   int32_t aac-drc-cut-level = 127
D/CCodec  (17029):   int32_t aac-drc-effect-type = 3
D/CCodec  (17029):   int32_t aac-drc-output-loudness = -1
D/CCodec  (17029):   int32_t aac-encoded-target-level = -1
D/CCodec  (17029):   int32_t aac-max-output-channel_count = 8
D/CCodec  (17029):   int32_t aac-target-ref-level = 64
D/CCodec  (17029):   int32_t channel-count = 2
D/CCodec  (17029):   int32_t channel-mask = 0
D/CCodec  (17029):   int32_t max-output-channel-count = 8
D/CCodec  (17029):   string mime = "audio/raw"
D/CCodec  (17029):   int32_t sample-rate = 48000
D/CCodec  (17029):   int32_t android._config-pcm-encoding = 2
D/CCodec  (17029): }
I/CCodecConfig(17029): query failed after returning 20 values (BAD_INDEX)
D/MediaCodec(17029): keep callback message for reclaim
W/Codec2Client(17029): query -- param skipped: index = 1342179345.
W/Codec2Client(17029): query -- param skipped: index = 2415921170.
W/Codec2Client(17029): query -- param skipped: index = 1610614798.
D/CCodecBufferChannel(17029): [c2.android.aac.decoder#778] Created input block pool with allocatorID 16 => poolID 18 - OK (0)
I/CCodecBufferChannel(17029): [c2.android.aac.decoder#778] Created output block pool with allocatorID 16 => poolID 38 - OK
D/CCodecBufferChannel(17029): [c2.android.aac.decoder#778] Configured output block pool ids 38 => OK
D/CCodecConfig(17029): c2 config diff is   c2::u32 raw.channel-mask.value = 12
D/CCodecBuffers(17029): [c2.android.aac.decoder#778:Output[N]] popFromStashAndRegister: at 1000000000000us, output format changed to AMessage(what = 0x00000000) = {
D/CCodecBuffers(17029):   int32_t aac-drc-album-mode = 0
D/CCodecBuffers(17029):   int32_t aac-drc-boost-level = 127
D/CCodecBuffers(17029):   int32_t aac-drc-cut-level = 127
D/CCodecBuffers(17029):   int32_t aac-drc-effect-type = 3
D/CCodecBuffers(17029):   int32_t aac-drc-output-loudness = -1
D/CCodecBuffers(17029):   int32_t aac-encoded-target-level = -1
D/CCodecBuffers(17029):   int32_t aac-max-output-channel_count = 8
D/CCodecBuffers(17029):   int32_t aac-target-ref-level = 64
D/CCodecBuffers(17029):   int32_t channel-count = 2
D/CCodecBuffers(17029):   int32_t channel-mask = 12
D/CCodecBuffers(17029):   int32_t max-output-channel-count = 8
D/CCodecBuffers(17029):   string mime = "audio/raw"
D/CCodecBuffers(17029):   int32_t sample-rate = 48000
D/CCodecBuffers(17029):   int32_t android._config-pcm-encoding = 2
D/CCodecBuffers(17029): }
I/ple.application(17029): Background concurrent copying GC freed 347(59KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 10MB/20MB, paused 7us,16us total 444.467ms
D/CCodecConfig(17029): c2 config diff is   c2::u32 raw.crop.height = 1920
D/CCodecConfig(17029):   c2::u32 raw.crop.left = 0
D/CCodecConfig(17029):   c2::u32 raw.crop.top = 0
D/CCodecConfig(17029):   c2::u32 raw.crop.width = 1080
D/BufferPoolAccessor2.0(17029): bufferpool2 0x7d98f4141818 : 5(31457280 size) total buffers - 4(25165824 size) used buffers - 18/24 (recycle/alloc) - 6/21 (fetch/transfer)
D/BufferPoolAccessor2.0(17029): bufferpool2 0x7d98f411fd48 : 5(40960 size) total buffers - 0(0 size) used buffers - 19/24 (recycle/alloc) - 7/24 (fetch/transfer)
D/BufferPoolAccessor2.0(17029): evictor expired: 1, evicted: 1
D/BufferPoolAccessor2.0(17029): evictor expired: 1, evicted: 1
D/EGL_emulation(17029): app_time_stats: avg=7123.09ms min=152.15ms max=14094.02ms count=2
D/EGL_emulation(17029): app_time_stats: avg=3529.37ms min=17.19ms max=7041.56ms count=2
Application finished.
Exited (sigterm)
```

**Comment by danpham02** [comment]
Start_stop media module and end of tutorial challenge should be ready, though I haven't worked on them in a bit so they are still using the tts plugin.

**Pull request merged**
